version: "3.7"
services:
  backups:
    image: maximilianoteruel/backups:dev
    environment:
      - CRON_INCREMENTAL=0_3_*_*_*
      - CRON_FULL=30_3_15_*_*
    volumes:
      - volume_1_incremental:/usr/src/app/backup/src/incremental/1
      - volume_2_incremental_full:/usr/src/app/backup/src/incremental/2
      - volume_2_incremental_full:/usr/src/app/backup/src/full/2
      - volume_3_full:/usr/src/app/backup/src/full/3
      - backups_config:/root/.config
      - backups_log:/usr/src/app/log
      - backups_full:/usr/src/app/backup/full

volumes:
  volume_1_incremental:
  volume_2_incremental_full:
  volume_3_full:
  backups_config:
  backups_log:
  backups_full:
